sonar.projectKey=manoou_sonarqube-github-actions_7e36e09a-92e5-4a0c-98f7-95abb396e835

sonar.sources=app.py,calculator.py

sonar.tests=tests

sonar.exclusions=.venv/**,__pycache__/**,.pytest_cache/**
